### ISSUE TITLE
toprammer python3 not available on pip

### ISSUE THREAD

**Issue by df8oe** [mbuesch/toprammer#3]
As title says: Why is toprammer not available via pip for python3?

**Comment by mbuesch** [comment]
Hi. Thanks for your question.
The answer is pretty simple: Because I didn't think it was necessary, yet.
This is a very special purpose tool.

But I'm not against uploading it to pypi.
Do you think this would greatly improve user experience?

**Comment by df8oe** [comment]
Of course it is not a software "for the masses". But coding and repairing experts (like me) prefer software that can be installed from repositories (I am using Archlinux and many is AURs). Pythons great advantage is that pypi and pip are existing...

**Comment by mbuesch** [comment]
I just realized, that I did in fact publish toprammer some time ago on pypi.
https://pypi.org/project/toprammer/

I forgot. It has been a long time since. :)

I did not publish the latest version of it, though.
But I'll do that asap.

**Comment by mbuesch** [comment]
Done.
I'll also release a new version with a couple of fixes applied.

Thanks a lot for your report.

**Comment by df8oe** [comment]
Many thanks for your work - I love it :)

**Comment by mbuesch** [comment]
You're welcome :)

I just released version 0.19, too.
